plugins:
  faucet_enabled:
    default: true
    client: true
  faucet_open:
    default: true
    client: true
  faucet_user_limit:
    default: 2
    client: true
  faucet_daily_limit:
    default: 20
    client: true
  faucet_level_limit_set:
    default: 1
    client: true
    enum: "TrustLevelSetting"